### ISSUE TITLE
I can't update an existing workspace on Windows.

### ISSUE THREAD

**Issue by JulianGebhart** [data-henrik/watson-conversation-tool#1]
Steps to recreate:

1) Download a .JSON Workspace directly from Conversation API
2) Using the downloaded workspace to update an existing workspace
3) The following error occurs: UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 66: invalid start byte

` python wctool.py -u -id “bb21cd53-4c91-45e4-addc-6430ea09608e” -intents -entit                                                                                ies -counterexamples -dialog_nodes -i SalesConnectOutput.json                                                                                                   Namespace(createWorkspace=False, deleteWorkspace=False, fullWorkspace=False, get                                                                                Workspace=False, inFile='SalesConnectOutput.json', listWorkspaces=False, outFile                                                                                =None, updateWorkspace=True, workspaceID='\x93bb21cd53-4c91-45e4-addc-6430ea0960                                                                                8e\x94', wsCounterexamples=True, wsDescription=None, wsDialogNodes=True, wsEntit                                                                                ies=True, wsIntents=True, wsLang=None, wsMetadata=False, wsName=None)
Traceback (most recent call last):
  File "wctool.py", line 160, in <module>
    parms.inFile)
  File "wctool.py", line 114, in updateWorkspace
    metadata=payload['metadata'])
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\watson_developer_cloud\co                                                                                nversation_v1.py", line 1097, in update_workspace
    accept_json=True)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\watson_developer_cloud\wa                                                                                tson_developer_cloud_service.py", line 302, in request
    **kwargs)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\requests\api.py", line 58                                                                                , in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\requests\sessions.py", li                                                                                ne 504, in request
    prep = self.prepare_request(req)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\requests\sessions.py", li                                                                                ne 436, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\requests\models.py", line                                                                                 302, in prepare
    self.prepare_url(url, params)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\requests\models.py", line                                                                                 358, in prepare_url
    url = url.decode('utf8')
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 66: invalid                                                                                 start byte
`

**Comment by data-henrik** [comment]
returning this because of wrong character
