### ISSUE TITLE
CTRL+C

### ISSUE THREAD

**Issue by mcanonic** [data-henrik/watson-conversation-tool#6]
I would suggest to manage the CTRL+C signal inside your code since it is one of the two ways to exit. When I use ctrl+c I got this:
Please enter your input message:
^CTraceback (most recent call last):
  File "wctool.py", line 238, in <module>
    converse(parms.workspaceID)
  File "wctool.py", line 165, in converse
    minput = raw_input("\nPlease enter your input message:\n")
KeyboardInterrupt

which is an error message that should not appear when you use one of the method suggested to exit from the application.
Best,
M

**Comment by data-henrik** [comment]
Yes, nice to have to improve it but lower priority.
